name = "v20"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Stéphane Rivière"]
maintainers = ["Stéphane Rivière <sriviere@soweb.io>"]
maintainers-logins = ["github-username"]
[[depends-on]]
gnatcoll = "^23.0.0"
