name = "v20"
description = "v20 text based general purpose library"
version = "0.11"
tags = ["console", "general-purpose"]
authors = ["Stéphane Rivière"]
maintainers = ["Stéphane Rivière <sriviere@soweb.io>"]
maintainers-logins = ["sowebio"]
website = "https://github.com/sowebio/v20-alire"
licenses = "GPL-3.0-or-later"
project-files = ["v20.gpr"]
[[depends-on]]
gnatcoll = "^23.0.0"
